# Generated by Django 5.1.8 on 2025-04-22 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
    ]
