# Generated by Django 5.1.7 on 2025-05-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_auto_20250422_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='tenant',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='tenant_favicons/'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='subscription_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='subscription_plan',
            field=models.CharField(choices=[('free', 'Free Plan'), ('basic', 'Basic Plan'), ('premium', 'Premium Plan'), ('enterprise', 'Enterprise Plan')], default='free', max_length=50),
        ),
        migrations.AddField(
            model_name='tenant',
            name='subscription_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='accent_color',
            field=models.CharField(default='#FF5722', max_length=7),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='business_hours_end',
            field=models.TimeField(default='18:00'),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='business_hours_start',
            field=models.TimeField(default='09:00'),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='custom_css',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='date_format',
            field=models.CharField(default='DD/MM/YYYY', max_length=20),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='default_currency',
            field=models.CharField(default='INR', max_length=3),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='default_language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='enable_analytics',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='enable_forecasting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='enable_mobile_app',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='enable_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='secondary_color',
            field=models.CharField(default='#FFA000', max_length=7),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='weekend_days',
            field=models.CharField(default='0,6', max_length=20),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='business_type',
            field=models.CharField(choices=[('mango', 'Mango Wholesaler'), ('vegetable', 'Vegetable Wholesaler'), ('fruit', 'Mixed Fruit Wholesaler'), ('grocery', 'Grocery Wholesaler'), ('other', 'Other Wholesaler')], default='mango', max_length=50),
        ),
    ]
