# Generated by Django 5.1.8 on 2025-04-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', 'rename_date_to_invoice_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoice',
            name='cost_per_crate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Cost per Crate (₹)'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='no_of_crates',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='No of Crates'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='purchased_crates_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='No of Purchased Crates'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='purchased_crates_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Purchased Crate Price (₹)'),
        ),
    ]
