# Generated by Django 5.1.8 on 2025-04-04 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
    ]
