# Generated by Django 5.1.4 on 2025-03-22 18:45

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('lot_number', models.CharField(editable=False, max_length=10, unique=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('net_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_issuer_name', models.CharField(blank=True, choices=[('Abdul Rafi', 'Abdul Rafi'), ('Sadiq', 'Sadiq')], max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Purchase Invoice',
                'verbose_name_plural': 'Purchase Invoices',
            },
        ),
        migrations.CreateModel(
            name='PurchaseVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('area', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Damages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('due_to', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('amount_loss', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Damage',
                'verbose_name_plural': 'Damages',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('paid_by', models.CharField(max_length=100)),
                ('paid_to', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_invoice', to='Accounts.purchaseinvoice')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date', models.DateField(default=datetime.date.today)),
                ('payment_mode', models.CharField(choices=[('account_pay', 'Account Pay'), ('upi', 'UPI GPay / PhonePay'), ('cash', 'Cash')], default='cash', max_length=20, verbose_name='Payment Method')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='payment_attachments/', verbose_name='Payment Attachment')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='Accounts.purchaseinvoice')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField(default=0, editable=False)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('damage', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rotten', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('loading_unloading', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_products', to='Accounts.purchaseinvoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.product')),
            ],
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='Accounts.purchasevendor'),
        ),
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('lot_quantity', models.DecimalField(blank=True, decimal_places=2, help_text='Quantity (in kgs) used from the selected lot.', max_digits=12, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('vehicle_number', models.CharField(blank=True, max_length=50, null=True)),
                ('gross_vehicle_weight', models.DecimalField(blank=True, decimal_places=2, help_text='In Kilograms', max_digits=12, null=True)),
                ('reference', models.CharField(blank=True, max_length=200, null=True)),
                ('no_of_crates', models.IntegerField(blank=True, null=True)),
                ('cost_per_crate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('lot', models.ForeignKey(blank=True, help_text='Select a lot from a Purchase Invoice. (When used, mark as Sold.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_invoices', to='Accounts.purchaseinvoice')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='Accounts.customer')),
            ],
        ),
        migrations.CreateModel(
            name='SalesPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date', models.DateField(default=datetime.date.today)),
                ('payment_mode', models.CharField(choices=[('account_pay', 'Account Pay'), ('upi', 'UPI GPay / PhonePay'), ('cash', 'Cash')], default='cash', max_length=20, verbose_name='Payment Method')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='sales_payment_attachments/', verbose_name='Payment Attachment')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='Accounts.salesinvoice')),
            ],
        ),
        migrations.CreateModel(
            name='SalesProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField(editable=False)),
                ('gross_weight', models.DecimalField(decimal_places=2, help_text='Gross Weight in Kgs', max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, help_text='Discount as percentage', max_digits=5)),
                ('rotten', models.DecimalField(decimal_places=2, default=0, help_text='Rotten weight in Kgs', max_digits=12)),
                ('net_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Net Weight in Kgs after discount & rotten deduction', max_digits=12, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(blank=True, decimal_places=2, help_text='Total = Net Weight * Price', max_digits=12, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_products', to='Accounts.salesinvoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.product')),
            ],
        ),
    ]
