# Generated by Django 5.1.8 on 2025-04-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_alter_salesinvoice_cost_per_crate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='purchased_crates_total_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter a value here to override the calculated total (quantity * price). Leave blank to use calculation.', max_digits=10, null=True, verbose_name='Purchased crates total'),
        ),
        migrations.AlterField(
            model_name='packaging_invoice',
            name='cost_per_crate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Packaging cost per crate (₹)'),
        ),
        migrations.AlterField(
            model_name='packaging_invoice',
            name='no_of_crates',
            field=models.IntegerField(blank=True, null=True, verbose_name='No of Crates'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='cost_per_crate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Packaging cost per crate (₹)'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='purchased_crates_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Purchased price per crate (₹)'),
        ),
    ]
