# Generated by Django 5.1.4 on 2025-03-22 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesinvoice',
            name='lot',
        ),
        migrations.RemoveField(
            model_name='salesinvoice',
            name='lot_quantity',
        ),
        migrations.CreateModel(
            name='SalesLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity used from this lot (in kgs)', max_digits=12)),
                ('purchase_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.purchaseinvoice', verbose_name='Lot')),
                ('sales_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_lots', to='Accounts.salesinvoice')),
            ],
            options={
                'unique_together': {('sales_invoice', 'purchase_invoice')},
            },
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='lots',
            field=models.ManyToManyField(help_text='Select multiple lots and specify quantities used', through='Accounts.SalesLot', to='Accounts.purchaseinvoice', verbose_name='Lots Used'),
        ),
        migrations.AddField(
            model_name='salesproduct',
            name='lot',
            field=models.ForeignKey(blank=True, help_text='Link to specific lot usage', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Accounts.saleslot'),
        ),
    ]
