# Generated by Django 5.1.8 on 2025-04-02 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_salesinvoice_purchased_crates_total_override_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesinvoice',
            name='purchased_crates_total_override',
        ),
    ]
