# Generated by Django 5.1.8 on 2025-04-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_remove_salesinvoice_purchased_crates_total_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='purchased_crates_total_manual',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter the agreed total cost for purchased crates here.', max_digits=10, null=True, verbose_name='Purchased crates total'),
        ),
    ]
