# Generated by Django 5.1.4 on 2025-03-22 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_remove_salesinvoice_lot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleslot',
            name='purchase_invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_lots', to='Accounts.purchaseinvoice', verbose_name='Lot'),
        ),
    ]
