# Generated by Django 5.1.8 on 2025-04-02 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_salesinvoice_purchased_crates_total_manual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesinvoice',
            name='purchased_crates_total_manual',
        ),
    ]
