# Generated by Django 5.1.4 on 2025-03-23 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_alter_saleslot_purchase_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packaging_Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_crates', models.IntegerField(blank=True, null=True)),
                ('cost_per_crate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
