# Generated by Django 5.1.8 on 2025-04-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_packaging_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='purchased_crates_quantity',
            field=models.IntegerField(blank=True, help_text='Number of crates purchased from the customer', null=True, verbose_name='Purchased Crates Quantity'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='purchased_crates_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per purchased crate', max_digits=10, null=True, verbose_name='Purchased Crate Unit Price'),
        ),
        migrations.AlterField(
            model_name='purchaseproduct',
            name='damage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Damage (Kg)'),
        ),
        migrations.AlterField(
            model_name='purchaseproduct',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Discount (%)'),
        ),
        migrations.AlterField(
            model_name='purchaseproduct',
            name='rotten',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Rotten (Kg)'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='cost_per_crate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Outgoing Crate Unit Cost'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='no_of_crates',
            field=models.IntegerField(blank=True, null=True, verbose_name='Outgoing Crates Quantity'),
        ),
    ]
