# Generated by Django 5.1.7 on 2025-04-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0006_alter_purchaseproduct_damage_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="salesinvoice",
            old_name="date",
            new_name="invoice_date",
        ),
        migrations.AddField(
            model_name="salesinvoice",
            name="purchased_crates_quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="No of Purchased Crates",
            ),
        ),
        migrations.AddField(
            model_name="salesinvoice",
            name="purchased_crates_unit_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="Purchased price per crate (₹)",
            ),
        ),
        migrations.AlterField(
            model_name="packaging_invoice",
            name="cost_per_crate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Packaging cost per crate (₹)",
            ),
        ),
        migrations.AlterField(
            model_name="packaging_invoice",
            name="no_of_crates",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="No of Crates"
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="cost_per_crate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="Packaging cost per crate (₹)",
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="no_of_crates",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="No of Crates",
            ),
        ),
    ]
