# Generated by Django 5.1.8 on 2025-04-22 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_customer_credit_limit'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='saleslot',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='customer',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='damages',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='expense',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='packaging_invoice',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='product',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='purchasevendor',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='saleslot',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='invoice_number',
            field=models.CharField(editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='lot_number',
            field=models.CharField(editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='invoice_number',
            field=models.CharField(editable=False, max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('tenant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('tenant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='purchaseinvoice',
            unique_together={('tenant', 'invoice_number'), ('tenant', 'lot_number')},
        ),
        migrations.AlterUniqueTogether(
            name='purchasevendor',
            unique_together={('tenant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='salesinvoice',
            unique_together={('tenant', 'invoice_number')},
        ),
        migrations.AlterUniqueTogether(
            name='saleslot',
            unique_together={('tenant', 'sales_invoice', 'purchase_invoice')},
        ),
    ]
