# Generated by Django 5.1.8 on 2025-04-22 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_alter_saleslot_unique_together_customer_tenant_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='purchaseinvoice',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='purchasevendor',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='salesinvoice',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='saleslot',
            unique_together=set(),
        ),
    ]
