# Generated by Django 5.1.8 on 2025-04-05 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_remove_salesinvoice_purchased_crates_total_manual'),
        ('Accounts', '0007_rename_date_salesinvoice_invoice_date_and_more'),
    ]

    operations = [
    ]
