# Generated by Django 5.1.8 on 2025-04-22 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0009_require_tenant_field'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('tenant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('tenant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='purchaseinvoice',
            unique_together={('tenant', 'invoice_number'), ('tenant', 'lot_number')},
        ),
        migrations.AlterUniqueTogether(
            name='purchasevendor',
            unique_together={('tenant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='salesinvoice',
            unique_together={('tenant', 'invoice_number')},
        ),
        migrations.AlterUniqueTogether(
            name='saleslot',
            unique_together={('tenant', 'sales_invoice', 'purchase_invoice')},
        ),
    ]
