"""
Django settings for Mango_project project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
MEDIA_URL = ''
MEDIA_ROOT = BASE_DIR / ''

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-z5zrj!poao3_81z3&4#)hg29(xv7%pow%asnrqw+o*^l!@60b@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['habeeb321.pythonanywhere.com', '127.0.0.1', 'localhost']



# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'Accounts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
            os.path.join(BASE_DIR, 'Accounts', 'Template'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Mango_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
#Manually Added
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'Accounts', 'static'),
]
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

JAZZMIN_SETTINGS = {
    # title of the window (Will default to current_admin_site.site_title if absent or None)
    "site_title": "Star Mango Admin",
    # Title on the login screen (19 chars max) (defaults to current_admin_site.site_header if absent or None)
    "site_header": "Star Mango Supplies Korutla",
    # Logo to use for your site, must be present in static files
    "site_logo": None,
    # CSS classes that are applied to the logo
    "site_logo_classes": None,
    # Logo to use for login form in dark themes
    "login_logo": None,
    # Relative path to a favicon for your site, will default to site_logo if absent
    "site_icon": None,
    # Welcome text on the login screen
    "welcome_sign": "Welcome to Star Mango Supplies Admin",
    # Copyright on the footer
    "copyright": "Star Mango Ltd",

    # Field name on user model that contains avatar ImageField/URLField/Charfield or a callable that receives the user
    "user_avatar": None,

    # Top menu
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Dashboard", "url": "admin-dashboard", "permissions": ["auth.view_user"]},
        {"name": "Vendor Summary", "url": "/accounts/vendor-summary/"},
        {"name": "Customer Summary", "url": "/accounts/customer-summary/"},
    ],

    # Custom links to append to app groups, keyed on app name
    "custom_links": {
        "Accounts": [
            {"name": "Dashboard", "url": "admin-dashboard", "icon": "fas fa-chart-line"}
        ]
    },

    # Override app/model ordering by 3 ways
    "order_with_respect_to": ["Accounts", "auth"],
    "custom_app_order": ["Accounts", "auth"],
    # Specify how models are ordered specifically by app
    "custom_apps_models": {
        "Accounts": [
            "PurchaseInvoice",
            "SalesInvoice",
            "PurchaseVendor",
            "Customer",
            "Product",
            "Payment",
            "Expense",
            "Damages",
        ],
    },

    # Specify an app to hide all of its models
    "hide_apps": [],

    # Specify models to hide
    "hide_models": [],

    # Specify how models are ordered
    "show_sidebar": True,
    "navigation_expanded": True,

    # Icons
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "Accounts.PurchaseInvoice": "fas fa-shopping-cart",
        "Accounts.SalesInvoice": "fas fa-cash-register",
        "Accounts.Product": "fas fa-box",
        "Accounts.PurchaseVendor": "fas fa-users",
        "Accounts.Customer": "fas fa-user-friends",
        "Accounts.Expense": "fas fa-money-bill",
        "Accounts.Damages": "fas fa-exclamation-triangle"
    },

    # UI Settings - Simplified to use built-in functionality
    "custom_css": "css/custom_admin.css",
    "custom_js": None,
    "use_google_fonts_cdn": True,
    "show_ui_builder": True,
    "changeform_format": "horizontal_tabs",
    "related_modal_active": True,
    "form_size": "default",
    "theme": "default",
    "dark_mode_theme": None,
}

# Ensure jQuery is included properly
JAZZMIN_INCLUDE_JQUERY = True
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-primary",
    "accent": "accent-primary",
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "button_classes": {
        "primary": "btn-outline-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    },
    "select2_theme": "default",
    "field_control": {
        "input": "form-control",
        "select": "form-control",
        "textarea": "form-control",
        "number": "form-control",
        "checkbox": "custom-control-input",
        "radio": "custom-control-input"
    }
}

ROOT_URLCONF = 'Mango_project.urls'

# Add this setting to allow admin popups (which use iframes)
X_FRAME_OPTIONS = 'SAMEORIGIN'
